gree_sm_laravel/app/routes.php
<?php

# CSRF Protection
Route::when('*', 'csrf', ['POST', 'PUT', 'PATCH', 'DELETE']);

# Authentication
Route::get('login', 'AuthController@index')->before('guest');
Route::post('login', 'AuthController@store');
Route::get('logout', 'AuthController@destroy');

# Standard User Routes
Route::group(['before' => 'auth'], function() {
	Route::get('/', 'PageController@dashboard');

	Route::get('ajax/{data}', 'AjaxController@getAllData');

	Route::resource('cabang', 'CabangsController');
	Route::delete('cabangs/delete', 'CabangsController@destroySelected');

	Route::get('rangking', ['as' => 'rangking.index', 'uses' => 'CabangsController@indexRangking' ]);
	Route::get('rangking/{id}', 'CabangsController@showRangking');
	Route::patch('rangking/{id}', ['as' => 'rangking.update', 'uses' => 'CabangsController@updateRangking' ]);

	Route::resource('subcabang', 'SubcabangsController');
	Route::delete('subcabangs/delete', 'SubcabangsController@destroySelected');
	Route::patch('subcabangs/update', 'SubcabangsController@updateSelected');
	Route::patch('subcabangs/remove', 'SubcabangsController@removeSelected');

	Route::resource('dealer', 'DealersController');
	Route::delete('dealers/delete', 'DealersController@destroySelected');
	Route::patch('dealers/update', 'DealersController@updateSelected');
	Route::patch('dealers/remove', 'DealersController@removeSelected');

	Route::resource('product', 'ProductsController');
	Route::delete('products/delete', 'ProductsController@destroySelected');

	Route::resource('customer', 'CustomersController');
	Route::delete('customers/delete', 'CustomersController@destroySelected');

	Route::resource('sellin', 'SellinsController');
	Route::delete('sellins/delete', 'SellinsController@destroySelected');

	Route::resource('sellout', 'SelloutsController');
	Route::delete('sellouts/delete', 'SelloutsController@destroySelected');

	Route::get('stockopname', 'ProductsController@showStockopname');

	Route::get('report', 'CabangsController@showReport');
	Route::get('export/{page}/{type}', 'CabangsController@export');

	Route::resource('user', 'UsersController');
	Route::delete('users/delete', 'UsersController@destroySelected');
	Route::patch('users/update', 'UsersController@updateSelected');
	Route::patch('users/remove', 'UsersController@removeSelected');

	Route::resource('role', 'RolesController');

});


#IF Method not Allowed
// Route::any('{all}', function(){
//     return View::make('404');
// })->where('all', '.*');

gree_sm_laravel/app/models/Sellin.php
<?php

class Sellin extends \Eloquent {

	// Add your validation rules here
	public static $rules = [
		'sales_id' => 'required|integer',
		'cabang_id' => 'required|integer',
		'subcabang_id' => 'required|integer',
        'dealer_id' => 'required|integer',
		'datetime' => 'required|date'
	];

	// Don't forget to fill this array
	protected $fillable = ['sales_id', 'cabang_id', 'subcabang_id', 'dealer_id', 'datetime'];

	public function productins()
    {
    	return $this->hasMany('Productin');

    	// return $this->hasOne('Phone');
    	// return $this->hasManyThrough('Post', 'User');
     //    return $this->belongsTo('Phone');
     //    return $this->belongsToMany('Role');
     //    return $this->morphMany('Photo', 'imageable');
     //    return $this->morphToMany('Tag', 'taggable');
     //    return $this->morphedByMany('Post', 'taggable');
    }

    public function sales()
    {
    	return $this->belongsTo('User', 'sales_id');
    }

    public function cabang()
    {
    	return $this->belongsTo('Cabang');
    }

    public function subcabang()
    {
    	return $this->belongsTo('Subcabang');
    }

    public function dealer()
    {
    	return $this->belongsTo('Dealer');
    }



    public function getTotalQtyAttribute()
    {
        return $this->productins()->sum('quantity');
    }

    // public function getTotalAmountAttribute()
    // {
    //     $TotalPrice = $this->productins()->sum('price');
    //     return 'Rp ' . number_format($TotalPrice, 0, '', '.');
    // }

}

gree_sm_laravel/app/controllers/SellinsController.php
<?php

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Carbon\Carbon;

class SellinsController extends \BaseController {

	public function __construct()
    {
        $this->beforeFilter('auth.sellin');
    }

	/**
	 * Display a listing of sellins
	 *
	 * @return Response
	 */
	public function index()
	{
		$user = Sentinel::getUser();
		$userRole = $user->roles()->first()->slug;

		if ($userRole == 'sales') 
		{
			$sellins = Sellin::leftJoin('productins', 'productins.sellin_id', '=', 'sellins.id')
					->where('sellins.sales_id', '=', $user->id)
					->select('sellins.*', DB::raw('sum(productins.quantity*productins.price) AS total_price'))
					->groupBy('sellins.id')->get();
		} 
		elseif ($userRole == 'cabang') 
		{
			$sellins = Sellin::leftJoin('productins', 'productins.sellin_id', '=', 'sellins.id')
					->where('sellins.cabang_id', '=', $user->cabang->id)
					->select('sellins.*', DB::raw('sum(productins.quantity*productins.price) AS total_price'))
					->groupBy('sellins.id')->get();
		} 
		else 
		{
			$sellins = Sellin::leftJoin('productins', 'productins.sellin_id', '=', 'sellins.id')
					->select('sellins.*', DB::raw('sum(productins.quantity*productins.price) AS total_price'))
					->groupBy('sellins.id')->get();
		}

		return View::make('sellins.index', compact('sellins'));
	}

	/**
	 * Show the form for creating a new sellin
	 *
	 * @return Response
	 */
	public function create()
	{
		$user = Sentinel::getUser();
		$userRole = $user->roles()->first()->slug;

		$products = Product::all()->lists('name_and_code', 'id');

		if ($userRole == 'sales') {
			$sales = [$user->id => $user->full_name];
			$cabangs = [$user->cabang->id => $user->cabang->name];
			$subcabangs = Subcabang::where('cabang_id', $user->cabang->id)->lists('name', 'id');
			return View::make('sellins.create', compact('sales', 'cabangs', 'subcabangs', 'products'));
		} if ($userRole == 'cabang') {
			$salesRole = Sentinel::findRoleBySlug('sales');
			$sales = $salesRole->users()->where('cabang_id', $user->cabang->id)->select('id', DB::raw('CONCAT(first_name, " ", last_name) AS name'))->lists('name', 'id');
			$cabangs = [$user->cabang->id => $user->cabang->name];
			$subcabangs = Subcabang::where('cabang_id', $user->cabang->id)->lists('name', 'id');
			return View::make('sellins.create', compact('sales', 'cabangs', 'subcabangs', 'products'));
		} else {
			$cabangs = Cabang::lists('name', 'id');
			return View::make('sellins.create', compact('cabangs', 'products'));
		}
	}

	/**
	 * Store a newly created sellin in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		// get rule
		$rules = Sellin::$rules;

		// get inputs
		$inputs = Input::only('sales_id', 'datetime', 'cabang_id', 'subcabang_id', 'dealer_id');

		// convert date
		$datetime_origin = $inputs['datetime'];
		if ($inputs['datetime']) {
			$datetime = str_replace('- ', '', $inputs['datetime']);
			$dates = explode("/", $datetime);
			$inputs['datetime'] = $dates[1].'/'.$dates[0].'/'.$dates[2];
		}

		$inputs['transactions'] = [];
		$price_origin = [];

		$transactions_count = count(Input::get('product_id'));

		for ($key=0; $key < $transactions_count; $key++)
		{
			$rules['product_id.'.$key] = Productin::$rules['product_id'];
			$inputs['product_id.'.$key] = Input::get('product_id.'.$key);
			$rules['quantity.'.$key] = Productin::$rules['quantity'];
			$inputs['quantity.'.$key] = Input::get('quantity.'.$key);
			$rules['price.'.$key] = Productin::$rules['price'];
			array_push($price_origin, Input::get('price.'.$key));
			$inputs['price.'.$key] = str_replace('.', '', Input::get('price.'.$key));

			array_push($inputs['transactions'], $key);

		}

		// validate
		$validator = Validator::make($inputs, $rules);

		// check if cabang filled
		if (!empty($cabang_id = $inputs['cabang_id'])) {
			$inputs['subcabangs'] = Subcabang::where('cabang_id', $cabang_id)->lists('name', 'id');
			$salesRole = Sentinel::findRoleBySlug('sales');
			$inputs['sales'] = $salesRole->users()->where('cabang_id', $cabang_id)->select('id', DB::raw('CONCAT(first_name, " ", last_name) AS name'))->lists('name', 'id');
		}
		// check if subcabang filled
		if (!empty($subcabang_id = $inputs['subcabang_id'])) {
			$inputs['dealers'] = Dealer::where('subcabang_id', $subcabang_id)->lists('name', 'id');
		}

		if ($validator->fails())
		{
			// conver input to origin
			$inputs['datetime'] = $datetime_origin;

			for ($key=0; $key < $transactions_count; $key++)
			{
				$inputs['price.'.$key] = $price_origin[$key];
			}

			return Redirect::back()->withErrors($validator)->withInput($inputs);
		}

		// save Sellin
		$Sellin = Sellin::create([
			'sales_id' => $inputs['sales_id'],
			'cabang_id' => $inputs['cabang_id'],
			'subcabang_id' => $inputs['subcabang_id'],
			'dealer_id' => $inputs['dealer_id'],
			'datetime' => date_create_from_format('m/d/Y H:i', $inputs['datetime'])
		]);

		for ($key=0; $key < $transactions_count; $key++)
		{
			Productin::create([
				'product_id' => $inputs['product_id.'.$key],
				'quantity' => $inputs['quantity.'.$key],
				'price' => $inputs['price.'.$key],
				'sellin_id' => $Sellin->id
			]);
		}

		return Redirect::route('sellin.index')->withSuccess('Sellin has been created successfully');
	}

	/**
	 * Display the specified sellin.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		try 
		{
		 	$sellin = Sellin::findOrFail($id);
			
			$user = Sentinel::getUser();
			$userRole = $user->roles()->first()->slug;

			if ($userRole == 'sales') {
				$sales = [$user->id => $user->full_name];
				// if sales still on the same cabang
				if($sellin->cabang_id == $user->cabang->id) {
					$cabangs = [$user->cabang->id => $user->cabang->name];
				// if sales has move to to other cabang
				} else {
					$cabangs = Cabang::where('id', $sellin->cabang_id)->lists('name', 'id');
				}
			} elseif ($userRole == 'cabang') {
				$cabangs = [$user->cabang->id => $user->cabang->name];
				$salesRole = Sentinel::findRoleBySlug('sales');
				$sales = $salesRole->users()->where('cabang_id', $user->cabang->id)->select('id', DB::raw('CONCAT(first_name, " ", last_name) AS name'))->get()->lists('name', 'id');
			} else {
				$cabangs = Cabang::lists('name', 'id');
				$salesRole = Sentinel::findRoleBySlug('sales');
				$sales = $salesRole->users()->where('cabang_id', $sellin->cabang_id)->select('id', DB::raw('CONCAT(first_name, " ", last_name) AS name'))->get()->lists('name', 'id');
			}

		 	$subcabangs = Subcabang::where('cabang_id', $sellin->cabang_id)->lists('name', 'id');
		 	$dealers = Dealer::where('subcabang_id', $sellin->subcabang_id)->lists('name', 'id');

		 	$productins = Productin::where('sellin_id', $id)->get();
		 	foreach ($productins as &$productin) {
		 		$productin['price'] = number_format($productin['price'], 0, '', '.');
		 	}

		 	$products = Product::all()->lists('name_and_code', 'id');
		 	
		 	return View::make('sellins.edit', compact('sellin', 'sales', 'cabangs', 'subcabangs', 'dealers', 'productins', 'products'));
		} 
		catch (ModelNotFoundException $ex) 
		{
		  	return Redirect::route('sellin.index');
		}
	}

	/**
	 * Show the form for editing the specified sellin.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		return Response::view('404');
	}

	/**
	 * Update the specified sellin in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($sellin_id)
	{
		$user = Sentinel::getUser();
		$userRole = $user->roles()->first()->slug;

		// if sales has move to to other cabang
		if ($userRole == 'sales' && Input::get('cabang_id') != $user->cabang->id) {
			return Redirect::back()->withErrors(['Can not perform update or delete.<br>You already move to other Cabang.']);
		}

		// get rule
		$rules = Sellin::$rules;

		// get inputs
		$inputs = Input::only('sales_id', 'datetime', 'cabang_id', 'subcabang_id', 'dealer_id');

		// convert date
		$datetime_origin = $inputs['datetime'];
		if ($inputs['datetime']) {
			$datetime = str_replace('- ', '', $inputs['datetime']);
			$dates = explode("/", $datetime);
			$inputs['datetime'] = $dates[1].'/'.$dates[0].'/'.$dates[2];
		}

		$data_sellin = $inputs;

		$inputs['transactions'] = [];
		$price_origin = [];

		$transactions_count = count(Input::get('product_id'));

		for ($key=0; $key < $transactions_count; $key++)
		{
			$inputs['productin_id.'.$key] = Input::get('productin_id.'.$key);

			$rules['product_id.'.$key] = Productin::$rules['product_id'];
			$inputs['product_id.'.$key] = Input::get('product_id.'.$key);

			$rules['quantity.'.$key] = Productin::$rules['quantity'];
			$inputs['quantity.'.$key] = Input::get('quantity.'.$key);

			$rules['price.'.$key] = Productin::$rules['price'];
			array_push($price_origin, Input::get('price.'.$key));
			$inputs['price.'.$key] = str_replace('.', '', Input::get('price.'.$key));

			array_push($inputs['transactions'], $key);

		}

		// validate
		$validator = Validator::make($inputs, $rules);

		// check if cabang filled
		if (!empty($cabang_id = $inputs['cabang_id'])) {
			$inputs['subcabangs'] = Subcabang::where('cabang_id', $cabang_id)->lists('name', 'id');
			$salesRole = Sentinel::findRoleBySlug('sales');
			$inputs['sales'] = $salesRole->users()->where('cabang_id', $cabang_id)->select('id', DB::raw('CONCAT(first_name, " ", last_name) AS name'))->lists('name', 'id');
		}
		// check if subcabang filled
		if (!empty($subcabang_id = $inputs['subcabang_id'])) {
			$inputs['dealers'] = Dealer::where('subcabang_id', $subcabang_id)->lists('name', 'id');
		}

		if ($validator->fails())
		{
			// conver input to origin
			$inputs['datetime'] = $datetime_origin;
			for ($key=0; $key < $transactions_count; $key++)
			{
				$inputs['price.'.$key] = $price_origin[$key];
			}

			return Redirect::back()->withErrors($validator)->withInput($inputs);
		}



		// update sell in
		$sellin = Sellin::findOrFail($sellin_id);
		$sellin->sales_id = $inputs['sales_id'];

gree_sm_laravel/app/views/sellins/index.blade.php
@extends('master')

@section('css')
    <!-- Bootstrap time Picker -->
    <link rel="stylesheet" href="{{ URL::to('css/daterangepicker-bs3.css') }}">
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ URL::to('css/dataTables.bootstrap.min.css') }}">
@stop

@section('header')
    <section class="content-header title--print">
        <h4>PT GREE - Sell In&nbsp;&nbsp;<small>(<span class="DateStart"></span> - <span class="DateEnd"></span>)</small></h4>
    </section>
    <section class="content-header">
        <h1>Sell In <small>Data</small></h1>
        <ol class="breadcrumb">
            <li><a href="{{ URL::to('/')}}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="active">Sell In</li>
        </ol>
    </section>
@stop

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">

                {{Form::open(array('url' => 'sellins/delete', 'method' => 'DELETE', 'id'=>'FormDeleteSelected'))}}
                <div class="box-header with-border">

                    <!-- Button Controll -->
                    <a href="{{ URL::to('sellin/create')}}" class="btn btn-primary"><i class="fa fa-file"></i>&nbsp;&nbsp;New Sell In</a>&nbsp;&nbsp;
                    <button type="button" id="BtnDeleteSelected" class="btn btn-default" disabled><i class="fa fa-trash"></i>&nbsp;&nbsp;Delete Selected</button>
                    
                    <!-- Print Button -->
                    <button class="btn btn-warning pull-right btn--print"><i class="fa fa-print"></i>&nbsp;&nbsp;Print</button>

                    <!-- Export Button-->
                    <div class="dropdown pull-right" style="margin-right: 10px;">
                      <button id="dLabel" class="btn btn-success" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-download"></i>&nbsp;&nbsp;Export&nbsp;&nbsp;<span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu" aria-labelledby="dLabel">
                        <li><a href="{{ URL::to('export/sellin/xls')}}">Excel</a></li>
                        <li><a href="{{ URL::to('export/sellin/csv')}}">CSV</a></li>
                      </ul>
                    </div>

                    <!-- Filter Date Range -->
                    <div class="filter-on-head pull-right" style="margin-right: 10px;">
                        <label for="FilterDateRange">Filter Date: </label>
                        <div id="FilterDateRange" class="btn btn-default pull-right">
                            <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>&nbsp;&nbsp;
                            <span class="DateStart"></span> - <span class="DateEnd"></span>&nbsp;&nbsp;<b class="caret"></b>
                        </div>
                    </div>
                </div>
                <div class="box-body">

                    <table id="table" class="table table-bordered table-hover" width="100%">
                        <thead>
                            <tr>
                                <th width="10">
                                    <input type="checkbox" name="select_all" value="1" id="example-select-all">
                                </th>
                                <th>ID</th>
                                <th>Cabang</th>
                                <th>Sub Cabang</th>
                                <th>Dealer</th>
                                <th>Sales</th>
                                <th>Date</th>
                                {{-- <th>Time</th> --}}
                                <th>Total QTY</th>
                                <th>Total Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                        	@foreach($sellins as $key => $value)
	                            <tr href="{{ URL::to('sellin/' . $value->id) }}">
                                    <td disabled></td>
                                    <td>{{ $value->id }}</td>
                                    <td>{{ (empty($value->cabang->name))?'':$value->cabang->name }}</td>
                                    <td>{{ (empty($value->subcabang->name))?'':$value->subcabang->name }}</td>
                                    <td>{{ (empty($value->dealer->name))?'':$value->dealer->name }}</td>
	                                <td>{{ (empty($value->sales->first_name))?'':$value->sales->first_name }} {{ (empty($value->sales->last_name))?'':$value->sales->last_name }}</td>
                                    <td class="prettify-date text-center">{{ $value->datetime }}</td>
                                    {{-- <td class="prettify-time text-center">{{ $value->datetime }}</td> --}}
                                    <td class="text-right">{{ (empty($value->total_qty))?'':$value->total_qty }}</td>
                                    <td class="text-right">{{ (empty($value->total_price))?'':'Rp ' . number_format($value->total_price, 0, '', '.') }}</td>
	                            </tr>
	                        @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
                {{ Form::close() }}

            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
@stop

@section('js')
    <!-- DataTables -->
    <script src="{{ URL::to('js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ URL::to('js/dataTables.bootstrap.min.js') }}"></script>
    <!-- date-range-picker -->
    <script src="{{ URL::to('js/daterangepicker.js') }}"></script>
@stop

@section('scripts')
	<script>

    $.fn.dataTableExt.afnFiltering.push(
        function(oSettings, aData, iDataIndex) {
            var dateStart = Date.parse($(".DateStart").text());
            var dateEnd = Date.parse($(".DateEnd").text());
            var evalDate= Date.parse(aData[6]);

            // console.log(dateStart);
            // console.log(dateEnd);
            // console.log(aData[6]);
            // console.log(evalDate);

            if (isNaN(dateStart) || isNaN(dateEnd)) {
                return true;
            } else if (evalDate >= dateStart && evalDate <= dateEnd) { 
                return true;
            } else { 
                return false; 
            }
        }
    );

    $(function() {

        var $Table = $('#table').DataTable({
            // 'ajax': "{{ route('subcabang.index') }}",
            'columnDefs': [
                {
                    "targets": [ 1 ],
                    "visible": false,
                    "searchable": false
                },
                {
                    'targets': 0,
                    'searchable': false,
                    'orderable': false,
                    'className': 'dt-body-center',
                    'render': function (data, type, full, meta){
                        return '<input type="checkbox" name="ids[]" value="'+full[1]+'">';
                    }
                }
            ],
            'order': [[1, 'asc']]
        });

        // Handle click on "Select all" control
        $('#example-select-all').on('click', function(){
            // Get all rows with search applied
            var rows = $Table.rows({ 'search': 'applied' }).nodes();
            // Check/uncheck checkboxes for all rows in the table
            $('input[type="checkbox"]', rows).prop('checked', this.checked);
            checkCheckedCheckboxs();
        });

        // Handle click on checkbox to set state of "Select all" control
        $('#table tbody').on('change', 'input[type="checkbox"]', function(){
            // If checkbox is not checked
            if(!this.checked){
                var el = $('#example-select-all').get(0);
                // If "Select all" control is checked and has 'indeterminate' property
                if(el && el.checked && ('indeterminate' in el)){
                    // Set visual state of "Select all" control as 'indeterminate'
                    el.indeterminate = true;
                }
            }
            checkCheckedCheckboxs();
        });

        // If there any checked checkboxs
        var checkCheckedCheckboxs = function(){
            if ($('#table tbody').find('input[type="checkbox"]:checked').length == 0) {
                $('#BtnDeleteSelected').attr('disabled','disabled');
            } else {
                $('#BtnDeleteSelected').removeAttr('disabled');
            }
        }

        // on Delete
        $('#BtnDeleteSelected').click(function(ev){
            ev.preventDefault();
            alertify.confirm("Are you sure you want to delete selected items?", function () {
                $('#FormDeleteSelected').submit(); 
            });
        });

        // daterangepicker
        function cb(start, end) {
            if (isNaN(start) || isNaN(end)) {
                $('.DateStart').html('All');
                $('.DateEnd').html('Time');
            } else {
                $('.DateStart').html(start.format('MMMM D, YYYY'));
                $('.DateEnd').html(end.format('MMMM D, YYYY'));
            }
            $Table.draw();
        }
        cb(moment().startOf('month'), moment().endOf('month'));
        // cb('', '');
        $('#FilterDateRange').daterangepicker({
            ranges: {
               'All Time': [null, null],
               'Today': [moment(), moment()],
               'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
               'Last 7 Days': [moment().subtract(6, 'days'), moment()],
               'Last 30 Days': [moment().subtract(29, 'days'), moment()],
               'This Month': [moment().startOf('month'), moment().endOf('month')],
               'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            }
        }, cb);
        $('#FilterDateRange').data('daterangepicker').setStartDate(moment().startOf('month'));
        $('#FilterDateRange').data('daterangepicker').setEndDate(moment().endOf('month'));

    });
	</script>
@stop